<a href="https://colab.research.google.com/github/peteryu24/petercoding-python/blob/main/tensorflow_numpy_add.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
import numpy as np

t=tf.random.uniform([2,3],0,1)
n=np.random.uniform(0,1,[2,3])

print("tensor with tensorflow:\n",t,"\n")
print("ndarray with numpy:\n",n,"\n")

res=t+n
print("addition result:\n",res)

tensor with tensorflow:
 tf.Tensor(
[[0.02321553 0.6181867  0.24458003]
 [0.54218495 0.13277161 0.46940696]], shape=(2, 3), dtype=float32) 

ndarray with numpy:
 [[0.26729038 0.9988881  0.2914532 ]
 [0.38377283 0.75156401 0.31134202]] 

addition result:
 tf.Tensor(
[[0.29050592 1.6170747  0.5360333 ]
 [0.9259578  0.88433564 0.78074896]], shape=(2, 3), dtype=float32)
