<a href="https://colab.research.google.com/github/peteryu24/petercoding-python/blob/main/train_test_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
import numpy as np

digit=datasets.load_digits()
x_train,x_test,y_train,y_test=train_test_split(digit.data,digit.target,train_size=0.6)

s=svm.SVC(gamma=0.001)
s.fit(x_train,y_train)

res=s.predict(x_test)

conf=np.zeros((10,10))
for i in range(len(res)):
  conf[res[i]][y_test[i]]+=1
print(conf)

no_correct=0
for i in range(10):
  no_correct+=conf[i][i]
accuracy=no_correct/len(res) 
print("accuracy of the test is", accuracy*100, "%.")

[[61.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 73.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 78.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 83.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. 65.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 70.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. 71.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 63.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  1.  0. 70.  1.]
 [ 0.  0.  0.  0.  1.  2.  0.  0.  0. 77.]]
accuracy of the test is 98.88734353268428 %.
